---
- name: Add host to Checkmk server
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Send notify to Telegram
      community.general.telegram:
        token: "{{ api_token }}"
        api_args:
          chat_id: "{{ chat_ID }}"
          parse_mode: "markdown"
          text: |
            ```
            "huydv3 test Telegram"
            ```
          disable_web_page_preview: true
          disable_notification: true